### ISSUE TITLE
Error while repacking json to sdt

### ISSUE THREAD

**Issue by Ronald181381** [Dir-A/ReVN#1]
First off, thank you so much for making the tool

I used the text editor tool to convert the sdt files into json, then entered the translated text (in English) in the trans rows of the json files and finally used the tool again to repack the json files into sdt, but the tool displayed this error at the last step of the process
![image](https://github.com/user-attachments/assets/a35ff06f-b133-4194-baa6-97b5fbbc9a8b)

**Comment by Dir-A** [comment]
please check your json file format or upload the json file

**Comment by Ronald181381** [comment]
[seen1000.json](https://github.com/user-attachments/files/17038911/seen1000.json)
There's a total of 35 files, each one translated in the same way

I used translator++'s custom parser feature to select just the text in the trans rows and translated it

**Comment by Dir-A** [comment]
Extra inverted commas at the end of line 29、589、697、709

Incorrect Json format
```json
"tra": "<unk>...<unk>""
```

Correct Json Format
```json
"tra": "<unk>...<unk>"
```

**Comment by Ronald181381** [comment]
Yeah, I just realized that while experimenting, and the tool works perfectly after removing the extra ".

By the way, is there any way to remove the buffer size limit?

**Comment by Dir-A** [comment]
If you're asking if it's possible, there must be a way, it's just a pain in the arse.

**Comment by Ronald181381** [comment]
I see, guess I'll just manually shorten the text

Thanks again
